name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: Pass the version
        required: true
        type: string
      dry_run:
        description: Perform test without releasing
        type: choice
        required: true
        default: "true"
        options:
          - "true"
          - "false"  
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  setup:
    name: Prepare job settings
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.setup.outputs.version }}
      dry_run: ${{ steps.setup.outputs.dry_run }}
    steps:

      - name: Get the release version from the tag
        id: version_push
        shell: bash
        if: ${{ github.event_name == 'push' }}
        run: |
          echo ::set-output name=id::${GITHUB_REF#refs/tags/}
      - name: Get the release version from the input
        id: version_dispatch
        shell: bash
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo ::set-output name=version::$(echo ${{ inputs.version }} | xargs)
          echo ::set-output name=dry_run::${{ inputs.dry_run }}
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo ::set-output name=version::$(if [ -n "${{ steps.version_dispatch.outputs.version }}" ]; then echo "${{ steps.version_dispatch.outputs.version }}"; else echo "${{ steps.version_push.outputs.version }}"; fi)
          echo ::set-output name=dry_run::$(if [ -n "${{ steps.version_dispatch.outputs.dry_run }}" ]; then echo "${{ steps.version_dispatch.outputs.dry_run }}"; else echo "false"; fi)
      - name: Display settings
        shell: bash
        run: echo "Version ${{ steps.setup.outputs.version }}, Dry run- ${{ steps.setup.outputs.dry_run }}"
      - name: Fail if empty
        shell: bash
        run: |
          if [ -n "${{ steps.setup.outputs.version }}" ]; then exit 1; fi;
          if [ -n "${{ steps.setup.outputs.dry_run }}" ]; then exit 1; fi;
